### ISSUE TITLE
Being able to normatively reference JSON Schema

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-json-schema#133]
Our largest hurdle for this work item is being able to normatively reference JSON Schema.
JSON Schema has broad usage and industry adoption but isn't a standard in the eyes of the W3C, yet.

The [latest draft of JSON Schema](https://datatracker.ietf.org/doc/draft-bhutton-json-schema/01/) is being standardized in the IETF, though this make take some time, too much time for us to hit our REC goal. We can non-normatively refer to older versions of the spec. But I believe we need to normatively refer to at least one version of JSON Schema (@msporny @OR13 correct me if I'm wrong).

I believe our first step should be reaching out to contacts at the W3C and seeing if we can gain an exception for normatively referencing JSON Schema. I'm not certain how this process works. @iherman can you please advise sensible next steps?

**Comment by iherman** [comment]
@decentralgabe the first thing to do is to crosscheck the JSON Schema development process with the [W3C Normative References](https://www.w3.org/2013/09/normative-references) document. If we can have a reasonable set of arguments why JSON Schema can be referred to this way (just, as say, we can refer to schema.org, although it is not  a formal standard either) then we are fine.

I guess there is no problem with [Licensing](https://www.w3.org/2013/09/normative-references#licensing), and our answer to the [Scheduling question](https://www.w3.org/2013/09/normative-references#schedule) is relatively easy: references to JSON Schema is absolutely essential for this specification to move forward. I think the real question is [the stability of the referenced document](https://www.w3.org/2013/09/normative-references#whole) and this was, I guess, the problem with earlier cases of JSON Schema usage. I am not familiar enough with the JSON Schema developers' community and way of operations to answer this; hopefully you have good information.

It is also a question how sensitive you are on the latest changes/features in terms of our references. Maybe we can argue that the features we are referring to _are_ stable, and we are not sensitive on newer features (e.g., I know I am dependent on the 2019-09 version in [yml2vocab](https://github.com/w3c/yml2vocab) for example).

Can you look at those issues? If we have a reasonable set of arguments then we may decide to go ahead, though we may have to defend at later stage in our process.

**Comment by Relequestual** [comment]
Hello. I currently lead the JSON Schema project.
I recently replied to someone who had some similar questions: https://github.com/orgs/json-schema-org/discussions/3#discussioncomment-6290893. (I referenced this issue too.)

Happy to chat! Feel free to join our slack server!
I'm unlikely to be able to give a timly response in replies here, but feel free to reply in that thread.

**Comment by OR13** [comment]
@Relequestual I have enjoyed chatting with you on slack : )

I think we have resolved this issue, but I will confirm with others.

**Comment by decentralgabe** [comment]
this issue is resolved, and we normatively refer to JSON schema https://github.com/w3c/AB-memberonly/issues/179

**Comment by msporny** [comment]
> this issue is resolved, and we normatively refer to JSON schema [w3c/AB-memberonly#179](https://github.com/w3c/AB-memberonly/issues/179)

The question isn't if we normatively refer to JSON Schema, we have to do that... it's if the document linked to (specifically the features linked to) are stable, not going away, and that document will continue to exist over time. That's what we'd like to have a definitive answer from W3M or the W3C Process folks.

**Comment by OR13** [comment]
@iherman can we assign you? we've done everything we can on our side I think.

**Comment by iherman** [comment]
> @iherman can we assign you? we've done everything we can on our side I think.

Sure, but I am not sure what I could do that @decentralgabe could not. 

See https://github.com/w3c/strategy/issues/108, b.t.w., which is a pretty long-standing issue as you can see. The only thing we can do (and hope for) is to watch that issue.

(I get notifications for https://github.com/w3c/strategy/issues/108 so if this help, I am happy to serve as a conduit.)

**Comment by OR13** [comment]
I am confused then, why do we leave this issue open if editors think its done, and our staff contact does not know what to do?

@iherman @msporny  can you please clarify why this issue should remain open?

**Comment by msporny** [comment]
> @msporny can you please clarify why this issue should remain open?

We need to get a clear answer from the people that make decisions about stable references at W3C about whether or not the way we're referencing JSON Schema is adequate for a W3C REC. That person used to be @plehegar, but given the new organizational structure of W3C, and the way this stuff is handled now via the new councils, and the updates to the W3C Process, I don't know who the appropriate person is in order to ask them. @iherman might know, or might be saying that the way we're referencing JSON Schema may or may not be adequate based on how that issue that's linked to is resolved. IOW, JSON Schema is a down ref that you cannot get past by just including JSON Schema in the specification... and the document that's pointed to might not be adequate because it looks like it could change at any point. Ideally, you could point to a date-stamped spec and say "that one is the one this specification normatively references"... but then you have to make sure that spec is going to be around for (ideally) a decade or more.

You could close the issue, but then you don't get the answer you want to have before you go into CR... and it might result in not being able to publish as anything more than a CR because you don't have a stable reference to JSON Schema.

You need to find the person that can give you a definitive answer about how the Director (or FO Council) would evaluate whether or not this reference to JSON Schema is adequate. The W3C Process folks might be good to reach out to to try to figure out the current status on referring to external documents.

**Comment by OR13** [comment]
Seems blocked pending https://github.com/w3c/strategy/issues/108

Unless this issue is resolved I don't think we can advance this document.

**Comment by Relequestual** [comment]
> this issue is resolved, and we normatively refer to JSON schema https://github.com/w3c/AB-memberonly/issues/179

@decentralgabe for those of us who can't see into that repo... can you share what was discussed there and why it resolves this issue? Are you saying you are allowed to normativly refer to JSON Schema, or you just decided to for now?

**Comment by iherman** [comment]
@Relequestual 

> > this issue is resolved, and we normatively refer to JSON schema [w3c/AB-memberonly#179](https://github.com/w3c/AB-memberonly/issues/179)
> 
> @decentralgabe for those of us who can't see into that repo... can you share what was discussed there and why it resolves this issue? Are you saying you are allowed to normativly refer to JSON Schema, or you just decided to for now?

The conclusion of that thread actually leads to a (I believe) public comment: https://github.com/w3c/strategy/issues/108#issuecomment-1622092494
