### ISSUE TITLE
unresolvable https://www.w3.org/2022/credentials/v2/json-schema-credential-schema.json

### ISSUE THREAD

**Issue by mjfelis** [w3c/vc-json-schema#234]
GET https://www.w3.org/2022/credentials/v2/json-schema-credential-schema.json: not found

```json
{
  "id": "https://www.w3.org/2022/credentials/v2/json-schema-credential-schema.json",
  "type": "JsonSchema",
  "digestSRI": "sha384-S57yQDg1MTzF56Oi9DbSQ14u7jBy0RDdx0YbeV7shwhCS88G8SCXeFq82PafhCrW"
}
```

**Comment by iherman** [comment]
@decentralgabe sorry, I missed this one, it got lost among the after-vacation mail invasion :-)

To be honest, it is the first time I see this W3C URL. Is this really where we want to store the schema? I mean, is the URL cast in concrete by now? 

The reason I am asking because the VC URI landscape is fairly chaotic. Here are just some:

- https://www.w3.org/2018/credentials# — VCDM Vocabulary
- https://www.w3.org/ns/credentials/v2 — VCDM Context file
- https://w3id.org/security# — DI vocabulary
- https://w3id.org/security/data-integrity/v2 — DI context
- https://www.w3.org/ns/credentials/status# — Bitstring status list vocabulary

etc. Introducing now https://www.w3.org/2022/credentials/v2/ just adds to the mess.

Would it be possible to simply use https://www.w3.org/ns/credentials/json-schema.json (or something like that)?

Once we decide on this, I am happy to set up a redirection.

The other question: is this schema file reasonably stable? At some point we should "freeze" these files by putting them to the W3C site and not redirect to github...

cc-ing @msporny to be consistent with other URLs

**Comment by iherman** [comment]
> > https://www.w3.org/ns/credentials/json-schema.json
> 
> This is just the schema for v2.0, IIUC. We should version it. Perhaps something like:
> 
> https://www.w3.org/ns/credentials/json-schema/v2.json ?

Works for me.

**Comment by decentralgabe** [comment]
`https://www.w3.org/ns/credentials/json-schema/v2.json` works for me too

**Comment by iherman** [comment]
https://www.w3.org/ns/credentials/json-schema/v2.json is now alive, and redirects to https://w3c.github.io/vc-json-schema/schema/json-schema-credential-schema.json

**Comment by iherman** [comment]
I have raised PR #237 to replace the URL in the spec. This issue can be closed if and when that PR is merged.

@mjfelis you are welcome to adapt your application to the new URL; it should work now.
