### ISSUE TITLE
Should the non json-ld version have an `@context`

### ISSUE THREAD

**Issue by OR13** [w3c/vc-json-schema#7]
The DID Spec and the VC Data Model both have mandatory `@context` fields, which make it clear that these documents may support JSON-LD.

It seems likely that we should do the same thing here.

However, I have started with the assumption that those wishing to use these vc-json-schema documents do not understand JSON-LD nor will they tolerate extra parameters that are only required for JSON-LD interop.

Since we provide a demonstration of both ways to do things, its clearly possible to signal your intent to use JSON-LD by using the `@context` version, or not.

**Comment by glcohen** [comment]
I agree with your last sentence. I think it would be a good precedent to set to allow possible paths. Path 1 would be plain old JSON, unambiguously JSON (when we correct that signature). Path 2 would be valid JSON-LD.

The only question then is how would interop work? Would there be a preprocessor to de-LD-ify a path 2 schema? Would there be a preprocessor to LD-ify a path 1 schema? Or, would the spec require that publishing a schema results in publishing two documents.

I do not think including a context should be a requirement for those who do not wish to use LD. In the Workday ecosystem, our DID Documents have the requisite LD properties since we have no other choice when complying with the spec, even though we do not use LD. [The DID Spec](https://w3c.github.io/did-core/#contexts) explicitly requires a context property, even though it is only a _recommendation_ that...

> dereferencing the URIs results in a document containing machine-readable information about the context.

**Comment by OR13** [comment]
AFAIK there won't be interop without the none JSON-LD users accepting a context which they ignore.

JSON-LD is stricter than json, so if you want interop with it, you need at least the @context.

Given that we can add this one field and be guaranteed that the vc-json-schema can be used by both JSON-LD and regular JSON users, and we would be handling things the same way as the DID Spec and VC Spec, there is some historical bias to including the context for non JSON-LD users.

**Comment by glcohen** [comment]
> JSON-LD is stricter than json, so if you want interop with it, you need at least the @context.

this is the sticking point, isn't it. I don't see a way around it that isn't unfriendly to the users, so I think it is the best move.

**Comment by glcohen** [comment]
I have been swayed by some of the discussion in https://github.com/w3c/did-core/pull/142#issuecomment-565520532 and I think we should follow their lead.

**Comment by decentralgabe** [comment]
Related to #122; more discussion needed

**Comment by decentralgabe** [comment]
Removed entirely. Can be wrapped as a credential if needed. See #131
